# Generated by Django 6.0 on 2026-09-17 04:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaVies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicio', models.DateField(db_index=True, verbose_name='início do período')),
                ('periodo_fim', models.DateField(db_index=True, verbose_name='fim do período')),
                ('metrica', models.CharField(choices=[('TAXA_SELECAO', 'Taxa de seleção'), ('SCORE_MEDIO', 'Score médio recebido'), ('OVERRIDE', 'Taxa de override do gestor'), ('DISTRIBUICAO_AREA', 'Distribuição por área'), ('DISTRIBUICAO_LOCAL', 'Distribuição por localização'), ('TEMPO_DE_CASA', 'Distribuição por tempo de casa')], db_index=True, max_length=20, verbose_name='métrica')),
                ('grupo', models.CharField(db_index=True, max_length=140, verbose_name='grupo analisado')),
                ('tamanho_grupo', models.IntegerField(default=0, verbose_name='tamanho da amostra do grupo')),
                ('valor_grupo', models.FloatField(default=0, verbose_name='valor observado no grupo')),
                ('valor_referencia', models.FloatField(default=0, verbose_name='valor de referência (média geral)')),
                ('disparidade', models.FloatField(default=0, verbose_name='disparidade relativa à referência')),
                ('severidade', models.CharField(choices=[('OK', 'Sem disparidade relevante'), ('ATENCAO', 'Atenção'), ('CRITICO', 'Crítico')], db_index=True, default='OK', max_length=10, verbose_name='severidade')),
                ('recomendacao', models.TextField(blank=True, default='', verbose_name='recomendação acionável')),
                ('detalhes', models.JSONField(blank=True, default=dict, verbose_name='detalhes da apuração')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='criado em')),
            ],
            options={
                'verbose_name': 'auditoria de viés',
                'verbose_name_plural': 'auditorias de viés',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PrevisaoProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_referencia', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='data de referência')),
                ('metodo', models.CharField(choices=[('MONTE_CARLO', 'Simulação de Monte Carlo'), ('REGRESSAO', 'Regressão linear de progresso'), ('EVM', 'Valor agregado (EVM)')], db_index=True, default='MONTE_CARLO', max_length=16, verbose_name='método')),
                ('prazo_p10', models.DateField(blank=True, null=True, verbose_name='prazo P10')),
                ('prazo_p50', models.DateField(blank=True, null=True, verbose_name='prazo P50')),
                ('prazo_p80', models.DateField(blank=True, null=True, verbose_name='prazo P80')),
                ('prazo_p90', models.DateField(blank=True, null=True, verbose_name='prazo P90')),
                ('dias_desvio_p50', models.IntegerField(default=0, verbose_name='desvio do P50 sobre o prazo planejado (dias)')),
                ('probabilidade_atraso', models.FloatField(default=0, verbose_name='probabilidade de atraso')),
                ('custo_p50', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='custo final P50 (R$)')),
                ('custo_p80', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='custo final P80 (R$)')),
                ('custo_p90', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='custo final P90 (R$)')),
                ('probabilidade_estouro', models.FloatField(default=0, verbose_name='probabilidade de estouro de orçamento')),
                ('indice_confianca', models.FloatField(default=0, verbose_name='índice de confiança do dado de entrada')),
                ('fatores', models.JSONField(blank=True, default=list, verbose_name='fatores de risco explicáveis')),
                ('premissas', models.JSONField(blank=True, default=list, verbose_name='premissas da previsão')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='criado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previsoes_criadas', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previsoes', to='portfolio.project', verbose_name='projeto')),
            ],
            options={
                'verbose_name': 'previsão de projeto',
                'verbose_name_plural': 'previsões de projeto',
                'ordering': ['-data_referencia', '-criado_em'],
                'indexes': [models.Index(fields=['project', '-data_referencia'], name='analytics_p_project_05bf35_idx')],
            },
        ),
    ]
