# Generated by Django 6.0 on 2026-09-17 01:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160, verbose_name='nome')),
                ('tipo', models.CharField(choices=[('PROJETO', 'Projeto'), ('EQUIPE', 'Equipe'), ('AREA', 'Área'), ('DIRETO', 'Mensagem direta')], default='PROJETO', max_length=10, verbose_name='tipo')),
                ('descricao', models.TextField(blank=True, default='')),
                ('icone', models.CharField(default='message-circle', max_length=40, verbose_name='ícone')),
                ('cor', models.CharField(default='#6366F1', max_length=9, verbose_name='cor')),
                ('arquivada', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('participantes', models.ManyToManyField(blank=True, related_name='salas', to=settings.AUTH_USER_MODEL, verbose_name='participantes')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='portfolio.project')),
            ],
            options={
                'verbose_name': 'sala',
                'verbose_name_plural': 'salas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='mensagem')),
                ('reacoes', models.JSONField(blank=True, default=dict, verbose_name='reações')),
                ('anexo', models.FileField(blank=True, null=True, upload_to='chat/%Y/%m/', verbose_name='anexo')),
                ('editada', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to=settings.AUTH_USER_MODEL)),
                ('mencoes', models.ManyToManyField(blank=True, related_name='mensagens_mencionadas', to=settings.AUTH_USER_MODEL)),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostas', to='collab.mensagem')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='collab.sala')),
            ],
            options={
                'verbose_name': 'mensagem',
                'verbose_name_plural': 'mensagens',
                'ordering': ['criado_em'],
                'indexes': [models.Index(fields=['sala', '-criado_em'], name='collab_mens_sala_id_9c389e_idx')],
            },
        ),
    ]
