# Generated by Django 6.0 on 2026-09-17 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capabilities', '0001_initial'),
        ('portfolio', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='allocationrecommendation',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendacoes', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='allocationrecommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendacoes_recebidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='developmentaction',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_pdi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='developmentplan',
            name='responsavel_acompanhamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdis_acompanhados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='developmentplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='developmentaction',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes', to='capabilities.developmentplan'),
        ),
        migrations.AddField(
            model_name='employeeskill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfis_skill', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeetraining',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinamentos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internalopportunity',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades', to='portfolio.project'),
        ),
        migrations.AddField(
            model_name='internalopportunity',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oportunidades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='mentee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorias_como_mentee', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentorias_como_mentor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='opportunityapplication',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to='capabilities.internalopportunity'),
        ),
        migrations.AddField(
            model_name='opportunityapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidaturas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posicaochave',
            name='gestor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posicoes_gerenciadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='posicaochave',
            name='ocupante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posicoes_ocupadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectskillrequirement',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos_skill', to='portfolio.project'),
        ),
        migrations.AddField(
            model_name='skill',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivadas', to='capabilities.skill', verbose_name='capacidade pai'),
        ),
        migrations.AddField(
            model_name='projectskillrequirement',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos_projeto', to='capabilities.skill'),
        ),
        migrations.AddField(
            model_name='posicaochave',
            name='skills_criticas',
            field=models.ManyToManyField(blank=True, related_name='posicoes_chave', to='capabilities.skill'),
        ),
        migrations.AddField(
            model_name='perfilnivel',
            name='skill',
            field=models.ForeignKey(blank=True, help_text='Deixe vazio para aplicar a regra geral do catálogo.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='criterios_nivel', to='capabilities.skill'),
        ),
        migrations.AddField(
            model_name='mentorship',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentorias', to='capabilities.skill'),
        ),
        migrations.AddField(
            model_name='internalopportunity',
            name='skills_requeridas',
            field=models.ManyToManyField(blank=True, related_name='oportunidades', to='capabilities.skill'),
        ),
        migrations.AddField(
            model_name='employeeskill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfis', to='capabilities.skill'),
        ),
        migrations.AddField(
            model_name='developmentaction',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_desenvolvimento', to='capabilities.skill'),
        ),
        migrations.AddField(
            model_name='busfactoralert',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_bus_factor', to='capabilities.skill'),
        ),
        migrations.AddField(
            model_name='skillassessment',
            name='avaliador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliacoes_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skillassessment',
            name='employee_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='capabilities.employeeskill'),
        ),
        migrations.AddField(
            model_name='skillcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='capabilities.skillcategory', verbose_name='categoria pai'),
        ),
        migrations.AddField(
            model_name='skill',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='capabilities.skillcategory', verbose_name='categoria'),
        ),
        migrations.AddField(
            model_name='skilldemandforecast',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previsoes', to='capabilities.skill'),
        ),
        migrations.AddField(
            model_name='skillendorsement',
            name='employee_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endossos', to='capabilities.employeeskill'),
        ),
        migrations.AddField(
            model_name='skillendorsement',
            name='endorser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endossos_feitos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skillevidence',
            name='employee_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='capabilities.employeeskill'),
        ),
        migrations.AddField(
            model_name='skillevidence',
            name='validador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_validadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skillhistory',
            name='employee_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='capabilities.employeeskill'),
        ),
        migrations.AddField(
            model_name='skillhistory',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historicos_skill', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='successionplan',
            name='posicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucessores', to='capabilities.posicaochave'),
        ),
        migrations.AddField(
            model_name='successionplan',
            name='sucessor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planos_sucessao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sugestaopromocao',
            name='employee_skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sugestoes', to='capabilities.employeeskill'),
        ),
        migrations.AddField(
            model_name='sugestaopromocao',
            name='validado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promocoes_validadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='training',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treinamentos', to='capabilities.skill'),
        ),
        migrations.AddField(
            model_name='employeetraining',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participacoes', to='capabilities.training'),
        ),
        migrations.AddIndex(
            model_name='allocationrecommendation',
            index=models.Index(fields=['task', '-score'], name='capabilitie_task_id_17f9fb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='opportunityapplication',
            unique_together={('opportunity', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='projectskillrequirement',
            unique_together={('project', 'skill')},
        ),
        migrations.AlterUniqueTogether(
            name='perfilnivel',
            unique_together={('skill', 'nivel')},
        ),
        migrations.AddIndex(
            model_name='employeeskill',
            index=models.Index(fields=['skill', 'nivel_atual'], name='capabilitie_skill_i_f86be1_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeskill',
            index=models.Index(fields=['user', 'status'], name='capabilitie_user_id_9b96fa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employeeskill',
            unique_together={('user', 'skill')},
        ),
        migrations.AddIndex(
            model_name='skillassessment',
            index=models.Index(fields=['employee_skill', 'tipo'], name='capabilitie_employe_80c023_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['tipo', 'status'], name='capabilitie_tipo_d9b47b_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['criticidade'], name='capabilitie_critici_6df835_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='skilldemandforecast',
            unique_together={('skill', 'periodo')},
        ),
        migrations.AlterUniqueTogether(
            name='skillendorsement',
            unique_together={('employee_skill', 'endorser')},
        ),
        migrations.AlterUniqueTogether(
            name='successionplan',
            unique_together={('posicao', 'sucessor')},
        ),
        migrations.AlterUniqueTogether(
            name='employeetraining',
            unique_together={('user', 'training')},
        ),
    ]
