# Generated by Django 6.0 on 2026-09-17 23:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversaIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Nova conversa', max_length=200, verbose_name='título')),
                ('criado_em', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversas_ia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'conversa com o assistente',
                'verbose_name_plural': 'conversas com o assistente',
                'ordering': ['-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='MensagemIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('USUARIO', 'Usuário'), ('ASSISTENTE', 'Assistente')], max_length=12)),
                ('texto', models.TextField(verbose_name='texto')),
                ('ferramentas', models.JSONField(blank=True, default=list, verbose_name='ferramentas usadas')),
                ('fontes', models.JSONField(blank=True, default=list, verbose_name='fontes')),
                ('provedor', models.CharField(blank=True, default='', max_length=40, verbose_name='provedor')),
                ('modelo', models.CharField(blank=True, default='', max_length=80)),
                ('duracao_ms', models.PositiveIntegerField(default=0)),
                ('util', models.BooleanField(blank=True, null=True, verbose_name='avaliada como útil')),
                ('comentario', models.TextField(blank=True, default='', verbose_name='comentário da avaliação')),
                ('criado_em', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='ia.conversaia')),
            ],
            options={
                'verbose_name': 'mensagem do assistente',
                'verbose_name_plural': 'mensagens do assistente',
                'ordering': ['criado_em'],
                'indexes': [models.Index(fields=['conversa', 'criado_em'], name='ia_mensagem_convers_748789_idx')],
            },
        ),
    ]
