# Generated by Django 6.0 on 2026-09-17 01:21

import apps.core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=140, verbose_name='nome')),
                ('evento', models.CharField(db_index=True, max_length=80, verbose_name='evento')),
                ('condicao_json', models.JSONField(blank=True, default=dict, verbose_name='condição')),
                ('canais', models.JSONField(blank=True, default=list, verbose_name='canais')),
                ('nivel', models.CharField(choices=[('INFO', 'Informativo'), ('SUCESSO', 'Sucesso'), ('ALERTA', 'Alerta'), ('CRITICO', 'Crítico')], default='INFO', max_length=12)),
                ('destinatarios', models.JSONField(blank=True, default=list, verbose_name='destinatários')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'regra de notificação',
                'verbose_name_plural': 'regras de notificação',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80, unique=True, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='descrição')),
                ('permissoes', models.JSONField(blank=True, default=list, verbose_name='permissões')),
                ('is_sistema', models.BooleanField(default=False, verbose_name='papel de sistema')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'papel',
                'verbose_name_plural': 'papéis',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=140, verbose_name='nome')),
                ('url', models.URLField(verbose_name='URL')),
                ('eventos', models.JSONField(blank=True, default=list, verbose_name='eventos')),
                ('ativo', models.BooleanField(default=True)),
                ('secreto', models.CharField(blank=True, default='', max_length=80)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'webhook',
                'verbose_name_plural': 'webhooks',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='e-mail')),
                ('nome', models.CharField(max_length=180, verbose_name='nome')),
                ('perfil', models.CharField(choices=[('ADMIN', 'Administrador'), ('EXECUTIVO', 'Executivo (C-Level)'), ('PMO', 'PMO'), ('GERENTE', 'Gerente de Projetos'), ('LIDER', 'Líder Técnico'), ('MEMBRO', 'Membro de Equipe'), ('RH', 'RH / DHO'), ('STAKEHOLDER', 'Stakeholder')], db_index=True, default='MEMBRO', max_length=20, verbose_name='perfil')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatares/', verbose_name='avatar')),
                ('avatar_url', models.URLField(blank=True, default='', verbose_name='URL do avatar')),
                ('iniciais', models.CharField(blank=True, default='', max_length=4, verbose_name='iniciais')),
                ('cor', models.CharField(default='#3B82F6', max_length=9, verbose_name='cor')),
                ('icone', models.CharField(blank=True, default='user', max_length=40, verbose_name='ícone')),
                ('cargo', models.CharField(blank=True, default='', max_length=140, verbose_name='cargo')),
                ('area', models.CharField(blank=True, db_index=True, default='', max_length=140, verbose_name='área')),
                ('localizacao', models.CharField(blank=True, default='', max_length=140, verbose_name='localização')),
                ('fuso_horario', models.CharField(blank=True, default='America/Sao_Paulo', max_length=64, verbose_name='fuso horário')),
                ('data_admissao', models.DateField(blank=True, null=True, verbose_name='data de admissão')),
                ('custo_hora', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='custo/hora (R$)')),
                ('capacidade_semanal_horas', models.DecimalField(decimal_places=2, default=40, max_digits=5, verbose_name='capacidade semanal (h)')),
                ('custo_hora_visivel', models.BooleanField(default=False, verbose_name='custo visível a todos')),
                ('tema', models.CharField(default='system', max_length=10, verbose_name='tema')),
                ('densidade', models.CharField(default='padrao', max_length=12, verbose_name='densidade')),
                ('idioma', models.CharField(default='pt-BR', max_length=8, verbose_name='idioma')),
                ('aceita_recomendacoes', models.BooleanField(default=True, verbose_name='consentiu uso em recomendações de alocação')),
                ('disponivel_para_mentoria', models.BooleanField(default=False, verbose_name='disponível para mentoria')),
                ('interesses', models.JSONField(blank=True, default=list, verbose_name='interesses')),
                ('is_staff', models.BooleanField(default=False, verbose_name='acesso ao admin')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo no sistema')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('gestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liderados', to=settings.AUTH_USER_MODEL, verbose_name='gestor')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
                'ordering': ['nome'],
            },
            managers=[
                ('objects', apps.core.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('arquivo', models.FileField(upload_to='anexos/%Y/%m/', verbose_name='arquivo')),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
                ('mime', models.CharField(blank=True, default='', max_length=120)),
                ('tamanho', models.PositiveBigIntegerField(default=0)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anexos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'anexo',
                'verbose_name_plural': 'anexos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=140, verbose_name='nome')),
                ('token', models.CharField(default=apps.core.models.gerar_token_publico, max_length=64, unique=True)),
                ('escopos', models.JSONField(blank=True, default=list, verbose_name='escopos')),
                ('ativo', models.BooleanField(default=True)),
                ('expira_em', models.DateTimeField(blank=True, null=True)),
                ('ultimo_uso', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_api', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'token de API',
                'verbose_name_plural': 'tokens de API',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_nome', models.CharField(blank=True, default='', max_length=180)),
                ('user_cor', models.CharField(blank=True, default='#3B82F6', max_length=9)),
                ('verbo', models.CharField(max_length=60, verbose_name='verbo')),
                ('entidade', models.CharField(db_index=True, max_length=80, verbose_name='entidade')),
                ('entidade_id', models.CharField(blank=True, default='', max_length=64)),
                ('entidade_nome', models.CharField(blank=True, default='', max_length=200)),
                ('projeto_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('meta', models.JSONField(blank=True, default=dict, verbose_name='metadados')),
                ('criado_em', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'atividade',
                'verbose_name_plural': 'atividades',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_nome', models.CharField(blank=True, default='', max_length=180)),
                ('entidade', models.CharField(db_index=True, max_length=80, verbose_name='entidade')),
                ('entidade_id', models.CharField(blank=True, default='', max_length=64, verbose_name='id da entidade')),
                ('acao', models.CharField(choices=[('CRIAR', 'Criação'), ('ATUALIZAR', 'Atualização'), ('EXCLUIR', 'Exclusão'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('EXPORTAR', 'Exportação'), ('APROVAR', 'Aprovação'), ('ALOCAR', 'Alocação'), ('VALIDAR', 'Validação de capacidade')], db_index=True, max_length=20, verbose_name='ação')),
                ('valores_anteriores', models.JSONField(blank=True, default=dict)),
                ('valores_novos', models.JSONField(blank=True, default=dict)),
                ('justificativa', models.TextField(blank=True, default='')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=300)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de auditoria',
                'verbose_name_plural': 'registros de auditoria',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('texto', models.TextField(verbose_name='texto')),
                ('reacoes', models.JSONField(blank=True, default=dict, verbose_name='reações')),
                ('resolvido', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('mencoes', models.ManyToManyField(blank=True, related_name='mencoes', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='core.comentario')),
            ],
            options={
                'verbose_name': 'comentário',
                'verbose_name_plural': 'comentários',
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='CustomReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=140, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, default='')),
                ('widgets_json', models.JSONField(blank=True, default=list, verbose_name='widgets')),
                ('agendamento', models.CharField(blank=True, default='', max_length=80, verbose_name='agendamento (cron)')),
                ('destinatarios', models.JSONField(blank=True, default=list, verbose_name='destinatários')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'relatório customizado',
                'verbose_name_plural': 'relatórios customizados',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='DashboardLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=140, verbose_name='nome')),
                ('widgets_json', models.JSONField(blank=True, default=list, verbose_name='widgets')),
                ('is_default', models.BooleanField(default=False, verbose_name='padrão')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'layout de dashboard',
                'verbose_name_plural': 'layouts de dashboard',
                'ordering': ['-is_default', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('mensagem', models.TextField(blank=True, default='')),
                ('nivel', models.CharField(choices=[('INFO', 'Informativo'), ('SUCESSO', 'Sucesso'), ('ALERTA', 'Alerta'), ('CRITICO', 'Crítico')], db_index=True, default='INFO', max_length=12)),
                ('icone', models.CharField(default='bell', max_length=40)),
                ('cor', models.CharField(blank=True, default='', max_length=9)),
                ('link', models.CharField(blank=True, default='', max_length=300, verbose_name='link')),
                ('entidade', models.CharField(blank=True, default='', max_length=80)),
                ('entidade_id', models.CharField(blank=True, default='', max_length=64)),
                ('lida', models.BooleanField(db_index=True, default=False)),
                ('canal', models.CharField(default='IN_APP', max_length=20)),
                ('criado_em', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notificação',
                'verbose_name_plural': 'notificações',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='SavedFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=140, verbose_name='nome')),
                ('modulo', models.CharField(db_index=True, max_length=80, verbose_name='módulo')),
                ('criterios_json', models.JSONField(blank=True, default=dict, verbose_name='critérios')),
                ('icone', models.CharField(default='filter', max_length=40, verbose_name='ícone')),
                ('cor', models.CharField(default='#6366F1', max_length=9, verbose_name='cor')),
                ('compartilhado', models.BooleanField(default=False, verbose_name='compartilhado com a equipe')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filtros_salvos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'filtro salvo',
                'verbose_name_plural': 'filtros salvos',
                'ordering': ['modulo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escopo', models.CharField(choices=[('GLOBAL', 'Global'), ('PORTFOLIO', 'Portfólio'), ('PROGRAMA', 'Programa'), ('PROJETO', 'Projeto'), ('PESSOAL', 'Pessoal')], default='GLOBAL', max_length=20, verbose_name='escopo')),
                ('escopo_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='id do escopo')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='core.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papeis', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'vínculo de papel',
                'verbose_name_plural': 'vínculos de papel',
            },
        ),
        migrations.CreateModel(
            name='UserViewPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contexto', models.CharField(max_length=80, verbose_name='contexto')),
                ('tipo_visualizacao', models.CharField(choices=[('GANTT', 'Gantt'), ('KANBAN', 'Kanban'), ('LISTA', 'Lista'), ('CALENDARIO', 'Calendário'), ('TIMELINE', 'Timeline'), ('MATRIZ', 'Matriz'), ('GRAFO', 'Grafo'), ('DASHBOARD', 'Dashboard')], default='LISTA', max_length=20)),
                ('configuracao_json', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias_visao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'preferência de visualização',
                'verbose_name_plural': 'preferências de visualização',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['perfil', 'ativo'], name='core_user_perfil_872fa1_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['area'], name='core_user_area_694ec6_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['entidade', 'entidade_id'], name='core_auditl_entidad_1d70c7_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-timestamp'], name='core_auditl_timesta_189a84_idx'),
        ),
        migrations.AddIndex(
            model_name='comentario',
            index=models.Index(fields=['content_type', 'object_id'], name='core_coment_content_170b87_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['user', 'lida', '-criado_em'], name='core_notifi_user_id_7f253c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role', 'escopo', 'escopo_id')},
        ),
        migrations.AlterUniqueTogether(
            name='userviewpreference',
            unique_together={('user', 'contexto')},
        ),
    ]
