# Generated by Django 6.0 on 2026-09-17 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='paleta',
            field=models.CharField(default='sgp', max_length=40, verbose_name='paleta de cores'),
        ),
        migrations.AddField(
            model_name='user',
            name='tema_custom',
            field=models.JSONField(blank=True, default=dict, verbose_name='tema personalizado'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tema',
            field=models.CharField(default='system', max_length=10, verbose_name='modo de cor'),
        ),
    ]
