# Generated by Django 6.0 on 2026-09-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_paleta_user_tema_custom_alter_user_tema'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='editado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='editado em'),
        ),
    ]
