# Generated by Django 6.0 on 2026-09-17 09:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaAjuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rota', models.CharField(max_length=160, unique=True, verbose_name='rota')),
                ('titulo', models.CharField(max_length=160, verbose_name='título da página')),
                ('grupo', models.CharField(choices=[('Fundamentos', 'Fundamentos'), ('Visão geral', 'Visão geral'), ('Portfólio', 'Portfólio'), ('Execução', 'Execução'), ('Recursos e alocação', 'Recursos e alocação'), ('Financeiro', 'Financeiro'), ('Riscos e qualidade', 'Riscos e qualidade'), ('Capacidades e talentos', 'Capacidades e talentos'), ('Administração', 'Administração')], db_index=True, max_length=60, verbose_name='grupo')),
                ('icone', models.CharField(default='help-circle', max_length=40, verbose_name='ícone')),
                ('resumo', models.CharField(blank=True, default='', max_length=300, verbose_name='resumo')),
                ('para_que_serve', models.TextField(blank=True, default='', verbose_name='para que serve')),
                ('quando_usar', models.JSONField(blank=True, default=list, verbose_name='quando usar')),
                ('passos', models.JSONField(blank=True, default=list, verbose_name='passo a passo')),
                ('elementos', models.JSONField(blank=True, default=list, verbose_name='elementos da tela')),
                ('campos', models.JSONField(blank=True, default=list, verbose_name='campos')),
                ('indicadores', models.JSONField(blank=True, default=list, verbose_name='indicadores')),
                ('dicas', models.JSONField(blank=True, default=list, verbose_name='dicas')),
                ('limitacoes', models.JSONField(blank=True, default=list, verbose_name='o que não faz')),
                ('atalhos', models.JSONField(blank=True, default=list, verbose_name='atalhos')),
                ('doc', models.CharField(blank=True, default='', max_length=120, verbose_name='documento do manual')),
                ('permissoes', models.JSONField(blank=True, default=list, verbose_name='permissões de acesso')),
                ('ordem', models.PositiveIntegerField(default=100, verbose_name='ordem')),
                ('ativo', models.BooleanField(db_index=True, default=True, verbose_name='ativo')),
                ('visualizacoes', models.PositiveIntegerField(default=0, verbose_name='visualizações')),
                ('marcado_util', models.PositiveIntegerField(default=0, verbose_name='avaliações positivas')),
                ('marcado_inutil', models.PositiveIntegerField(default=0, verbose_name='avaliações negativas')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'guia de ajuda',
                'verbose_name_plural': 'guias de ajuda',
                'ordering': ['grupo', 'ordem', 'titulo'],
                'indexes': [models.Index(fields=['grupo', 'ordem'], name='ajuda_guiaa_grupo_33a491_idx')],
            },
        ),
        migrations.CreateModel(
            name='AjudaFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('util', models.BooleanField(default=True, verbose_name='foi útil')),
                ('comentario', models.TextField(blank=True, default='', verbose_name='comentário')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_ajuda', to=settings.AUTH_USER_MODEL)),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='ajuda.guiaajuda')),
            ],
            options={
                'verbose_name': 'avaliação de guia',
                'verbose_name_plural': 'avaliações de guia',
                'ordering': ['-criado_em'],
                'unique_together': {('guia', 'user')},
            },
        ),
    ]
