# Generated by Django 6.0 on 2026-09-17 01:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=120, verbose_name='categoria')),
                ('tipo', models.CharField(choices=[('CAPEX', 'CAPEX (investimento)'), ('OPEX', 'OPEX (operacional)')], default='OPEX', max_length=8, verbose_name='tipo')),
                ('centro_custo', models.CharField(blank=True, default='', max_length=80, verbose_name='centro de custo')),
                ('valor_planejado', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='valor planejado (R$)')),
                ('valor_realizado', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='valor realizado (R$)')),
                ('valor_comprometido', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='valor comprometido (R$)')),
                ('cor', models.CharField(default='#3B82F6', max_length=9, verbose_name='cor')),
                ('icone', models.CharField(default='wallet', max_length=40, verbose_name='ícone')),
                ('observacao', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to='portfolio.project')),
            ],
            options={
                'verbose_name': 'orçamento',
                'verbose_name_plural': 'orçamentos',
                'ordering': ['project', 'categoria'],
                'unique_together': {('project', 'categoria', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DESPESA', 'Despesa'), ('RECEITA', 'Receita')], db_index=True, default='DESPESA', max_length=10, verbose_name='tipo')),
                ('categoria', models.CharField(blank=True, default='', max_length=120, verbose_name='categoria')),
                ('descricao', models.CharField(max_length=250, verbose_name='descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='valor (R$)')),
                ('data_competencia', models.DateField(db_index=True, verbose_name='data de competência')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='data de pagamento')),
                ('status', models.CharField(choices=[('PREVISTO', 'Previsto'), ('COMPROMETIDO', 'Comprometido'), ('REALIZADO', 'Realizado'), ('CANCELADO', 'Cancelado')], db_index=True, default='REALIZADO', max_length=16)),
                ('fornecedor', models.CharField(blank=True, default='', max_length=180, verbose_name='fornecedor/cliente')),
                ('documento', models.CharField(blank=True, default='', max_length=80, verbose_name='documento/NF')),
                ('centro_custo', models.CharField(blank=True, default='', max_length=80, verbose_name='centro de custo')),
                ('recorrente', models.BooleanField(default=False, verbose_name='recorrente')),
                ('observacao', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_aprovados', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos_criados', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='portfolio.project')),
                ('orcamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='finance.orcamento')),
            ],
            options={
                'verbose_name': 'lançamento',
                'verbose_name_plural': 'lançamentos',
                'ordering': ['-data_competencia'],
                'indexes': [models.Index(fields=['project', 'tipo', 'status'], name='finance_lan_project_f632a0_idx'), models.Index(fields=['data_competencia'], name='finance_lan_data_co_c7c217_idx')],
            },
        ),
        migrations.CreateModel(
            name='PrevisaoFluxoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(db_index=True, max_length=7, verbose_name='período (AAAA-MM)')),
                ('entradas_previstas', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('saidas_previstas', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('entradas_realizadas', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('saidas_realizadas', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('metodo', models.CharField(default='TENDENCIA', max_length=40, verbose_name='método')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previsoes_caixa', to='portfolio.project')),
            ],
            options={
                'verbose_name': 'previsão de fluxo de caixa',
                'verbose_name_plural': 'previsões de fluxo de caixa',
                'ordering': ['periodo'],
                'unique_together': {('project', 'periodo')},
            },
        ),
    ]
