# Generated by Django 6.0 on 2026-09-17 01:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capabilities', '0001_initial'),
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=240, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='descrição')),
                ('wbs', models.CharField(blank=True, default='', max_length=40, verbose_name='código EAP')),
                ('data_inicio', models.DateField(blank=True, db_index=True, null=True, verbose_name='início')),
                ('data_fim', models.DateField(blank=True, db_index=True, null=True, verbose_name='fim')),
                ('data_inicio_real', models.DateField(blank=True, null=True, verbose_name='início real')),
                ('data_fim_real', models.DateField(blank=True, null=True, verbose_name='fim real')),
                ('esforco_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='esforço estimado (h)')),
                ('esforco_real', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='esforço real (h)')),
                ('percentual_conclusao', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='percentual de conclusão')),
                ('status', models.CharField(choices=[('BACKLOG', 'Backlog'), ('A_FAZER', 'A fazer'), ('EM_ANDAMENTO', 'Em andamento'), ('EM_REVISAO', 'Em revisão'), ('BLOQUEADA', 'Bloqueada'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], db_index=True, default='A_FAZER', max_length=16)),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], db_index=True, default='MEDIA', max_length=12)),
                ('posicao_visual', models.FloatField(default=1000.0, verbose_name='posição no Kanban')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem na lista')),
                ('nivel', models.PositiveSmallIntegerField(default=0, verbose_name='nível na EAP')),
                ('colapsada', models.BooleanField(default=False, verbose_name='agrupador colapsado')),
                ('is_marco', models.BooleanField(default=False, verbose_name='é um marco')),
                ('critica', models.BooleanField(db_index=True, default=False, verbose_name='no caminho crítico')),
                ('folga_dias', models.IntegerField(default=0, verbose_name='folga (dias)')),
                ('restricao', models.CharField(blank=True, default='', max_length=60, verbose_name='restrição')),
                ('cor', models.CharField(blank=True, default='', max_length=9, verbose_name='cor')),
                ('icone', models.CharField(blank=True, default='', max_length=40, verbose_name='ícone')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='etiquetas')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtarefas', to='tasks.task', verbose_name='tarefa pai')),
                ('progresso_informado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progressos_informados', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='portfolio.project', verbose_name='projeto')),
                ('responsaveis_auxiliares', models.ManyToManyField(blank=True, related_name='tarefas_apoio', to=settings.AUTH_USER_MODEL, verbose_name='responsáveis auxiliares')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
            ],
            options={
                'verbose_name': 'tarefa',
                'verbose_name_plural': 'tarefas',
                'ordering': ['ordem', 'data_inicio', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=300, verbose_name='item')),
                ('concluido', models.BooleanField(default=False)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_checklist', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist', to='tasks.task')),
            ],
            options={
                'verbose_name': 'item de checklist',
                'verbose_name_plural': 'itens de checklist',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TaskDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FS', 'Término → Início'), ('SS', 'Início → Início'), ('FF', 'Término → Término'), ('SF', 'Início → Término')], default='FS', max_length=2, verbose_name='tipo')),
                ('lag', models.IntegerField(default=0, verbose_name='defasagem (dias)')),
                ('obrigatoria', models.BooleanField(default=True, verbose_name='obrigatória')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('predecessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucessoras', to='tasks.task')),
                ('successor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predecessoras', to='tasks.task')),
            ],
            options={
                'verbose_name': 'dependência',
                'verbose_name_plural': 'dependências',
            },
        ),
        migrations.CreateModel(
            name='TaskSkillRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_minimo', models.PositiveSmallIntegerField(default=3, verbose_name='nível mínimo')),
                ('peso', models.FloatField(default=1.0, verbose_name='peso')),
                ('obrigatorio', models.BooleanField(default=False, verbose_name='obrigatório')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos_tarefa', to='capabilities.skill')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos_skill', to='tasks.task')),
            ],
            options={
                'verbose_name': 'requisito de capacidade da tarefa',
                'verbose_name_plural': 'requisitos de capacidade da tarefa',
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'status'], name='tasks_task_project_b78682_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project', 'parent'], name='tasks_task_project_cf0938_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['responsavel', 'status'], name='tasks_task_respons_f7f12f_idx'),
        ),
        migrations.AddIndex(
            model_name='taskdependency',
            index=models.Index(fields=['predecessor'], name='tasks_taskd_predece_2f2b12_idx'),
        ),
        migrations.AddIndex(
            model_name='taskdependency',
            index=models.Index(fields=['successor'], name='tasks_taskd_success_c4e3bf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskdependency',
            unique_together={('predecessor', 'successor', 'tipo')},
        ),
        migrations.AlterUniqueTogether(
            name='taskskillrequirement',
            unique_together={('task', 'skill')},
        ),
    ]
