# Generated by Django 6.0 on 2026-09-17 01:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, default='', max_length=30, verbose_name='código')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('causa', models.TextField(blank=True, default='', verbose_name='causa raiz')),
                ('efeito', models.TextField(blank=True, default='', verbose_name='efeito potencial')),
                ('categoria', models.CharField(choices=[('ESCOPO', 'Escopo'), ('PRAZO', 'Prazo'), ('CUSTO', 'Custo'), ('QUALIDADE', 'Qualidade'), ('RECURSOS', 'Recursos / Capacidades'), ('TECNICO', 'Técnico'), ('REGULATORIO', 'Regulatório / Compliance'), ('SEGURANCA', 'Segurança da informação'), ('FORNECEDOR', 'Fornecedor'), ('MERCADO', 'Mercado'), ('PESSOAS', 'Pessoas'), ('OUTRO', 'Outro')], db_index=True, default='OUTRO', max_length=16, verbose_name='categoria')),
                ('probabilidade', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='probabilidade (1-5)')),
                ('impacto', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='impacto (1-5)')),
                ('severidade', models.PositiveSmallIntegerField(db_index=True, default=9, verbose_name='severidade (P×I)')),
                ('nivel', models.CharField(db_index=True, default='MEDIO', max_length=12, verbose_name='nível')),
                ('cor', models.CharField(default='#F59E0B', max_length=9, verbose_name='cor')),
                ('prob_residual', models.PositiveSmallIntegerField(default=0, verbose_name='probabilidade residual')),
                ('imp_residual', models.PositiveSmallIntegerField(default=0, verbose_name='impacto residual')),
                ('severidade_residual', models.PositiveSmallIntegerField(default=0, verbose_name='severidade residual')),
                ('estrategia', models.CharField(choices=[('EVITAR', 'Evitar'), ('MITIGAR', 'Mitigar'), ('TRANSFERIR', 'Transferir'), ('ACEITAR', 'Aceitar'), ('EXPLORAR', 'Explorar (oportunidade)'), ('ELEVAR', 'Elevar (oportunidade)'), ('COMPARTILHAR', 'Compartilhar')], default='MITIGAR', max_length=16, verbose_name='estratégia')),
                ('plano_resposta', models.TextField(blank=True, default='', verbose_name='plano de resposta')),
                ('contingencia', models.TextField(blank=True, default='', verbose_name='plano de contingência')),
                ('status', models.CharField(choices=[('IDENTIFICADO', 'Identificado'), ('EM_ANALISE', 'Em análise'), ('PLANEJADO', 'Com resposta planejada'), ('MITIGANDO', 'Mitigação em curso'), ('MONITORANDO', 'Monitorando'), ('OCORRIDO', 'Ocorrido'), ('ENCERRADO', 'Encerrado')], db_index=True, default='IDENTIFICADO', max_length=16)),
                ('data_identificacao', models.DateField(default=django.utils.timezone.localdate, verbose_name='identificado em')),
                ('data_limite', models.DateField(blank=True, null=True, verbose_name='prazo da resposta')),
                ('data_encerramento', models.DateField(blank=True, null=True, verbose_name='encerrado em')),
                ('custo_mitigacao', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='custo da mitigação (R$)')),
                ('valor_monetario_esperado', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='valor monetário esperado (R$)')),
                ('posicao_matriz_x', models.FloatField(blank=True, null=True, verbose_name='posição X na matriz')),
                ('posicao_matriz_y', models.FloatField(blank=True, null=True, verbose_name='posição Y na matriz')),
                ('gatilhos', models.JSONField(blank=True, default=list, verbose_name='gatilhos de monitoramento')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='etiquetas')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riscos_criados', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riscos', to='portfolio.project')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riscos', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
            ],
            options={
                'verbose_name': 'risco',
                'verbose_name_plural': 'riscos',
                'ordering': ['-severidade', '-atualizado_em'],
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, default='', max_length=30, verbose_name='código')),
                ('titulo', models.CharField(max_length=240, verbose_name='título')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='descrição')),
                ('tipo', models.CharField(choices=[('ISSUE', 'Issue'), ('ACAO_CORRETIVA', 'Ação corretiva'), ('MUDANCA', 'Solicitação de mudança'), ('IMPEDIMENTO', 'Impedimento'), ('DECISAO', 'Decisão pendente')], db_index=True, default='ISSUE', max_length=16, verbose_name='tipo')),
                ('prioridade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], db_index=True, default='MEDIA', max_length=12)),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('TRIAGEM', 'Em triagem'), ('EM_ANALISE', 'Em análise'), ('EM_ANDAMENTO', 'Em andamento'), ('AGUARDANDO', 'Aguardando terceiros'), ('RESOLVIDA', 'Resolvida'), ('FECHADA', 'Fechada'), ('CANCELADA', 'Cancelada')], db_index=True, default='ABERTA', max_length=16)),
                ('impacto', models.TextField(blank=True, default='', verbose_name='impacto')),
                ('solucao', models.TextField(blank=True, default='', verbose_name='solução aplicada')),
                ('data_abertura', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='aberta em')),
                ('data_limite', models.DateField(blank=True, null=True, verbose_name='prazo')),
                ('data_resolucao', models.DateField(blank=True, null=True, verbose_name='resolvida em')),
                ('esforco_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='esforço estimado (h)')),
                ('custo_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='custo estimado (R$)')),
                ('posicao_visual', models.FloatField(default=1000.0, verbose_name='posição no Kanban')),
                ('cor', models.CharField(default='#EF4444', max_length=9, verbose_name='cor')),
                ('icone', models.CharField(default='alert-circle', max_length=40, verbose_name='ícone')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='etiquetas')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='portfolio.project')),
                ('reportado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues_reportadas', to=settings.AUTH_USER_MODEL)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to=settings.AUTH_USER_MODEL)),
                ('risk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='risks.risk')),
            ],
            options={
                'verbose_name': 'issue',
                'verbose_name_plural': 'issues',
                'ordering': ['-prioridade', '-data_abertura'],
            },
        ),
        migrations.CreateModel(
            name='RiskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probabilidade', models.PositiveSmallIntegerField()),
                ('impacto', models.PositiveSmallIntegerField()),
                ('severidade', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('IDENTIFICADO', 'Identificado'), ('EM_ANALISE', 'Em análise'), ('PLANEJADO', 'Com resposta planejada'), ('MITIGANDO', 'Mitigação em curso'), ('MONITORANDO', 'Monitorando'), ('OCORRIDO', 'Ocorrido'), ('ENCERRADO', 'Encerrado')], max_length=16)),
                ('comentario', models.TextField(blank=True, default='')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_riscos', to=settings.AUTH_USER_MODEL)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='risks.risk')),
            ],
            options={
                'verbose_name': 'histórico de risco',
                'verbose_name_plural': 'históricos de risco',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='risk',
            index=models.Index(fields=['project', 'status'], name='risks_risk_project_f20864_idx'),
        ),
        migrations.AddIndex(
            model_name='risk',
            index=models.Index(fields=['severidade'], name='risks_risk_severid_0f918b_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['project', 'status'], name='risks_issue_project_fdac8e_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['tipo', 'status'], name='risks_issue_tipo_c3e0ab_idx'),
        ),
    ]
