# Generated by Django 6.0 on 2026-09-17 03:54

import apps.integrations.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_user_paleta_user_tema_custom_alter_user_tema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoIntegracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('projeto.criado', 'Projeto criado'), ('projeto.atualizado', 'Projeto atualizado'), ('projeto.concluido', 'Projeto concluído'), ('projeto.em_risco', 'Projeto entrou em risco'), ('tarefa.criada', 'Tarefa criada'), ('tarefa.concluida', 'Tarefa concluída'), ('tarefa.atrasada', 'Tarefa atrasada'), ('marco.concluido', 'Marco concluído'), ('risco.criado', 'Risco criado'), ('risco.critico', 'Risco crítico identificado'), ('issue.criada', 'Issue criada'), ('alocacao.criada', 'Alocação criada'), ('alocacao.conflito', 'Conflito de alocação'), ('orcamento.estourado', 'Orçamento estourado'), ('promocao.solicitada', 'Promoção solicitada'), ('promocao.aprovada', 'Promoção aprovada'), ('capacidade.evidencia_validada', 'Evidência validada'), ('capacidade.treinamento_concluido', 'Treinamento concluído')], db_index=True, max_length=40, verbose_name='tipo de evento')),
                ('entidade', models.CharField(blank=True, default='', max_length=80, verbose_name='entidade')),
                ('entidade_id', models.CharField(blank=True, default='', max_length=64, verbose_name='id da entidade')),
                ('projeto_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True, verbose_name='projeto')),
                ('titulo', models.CharField(blank=True, default='', max_length=200, verbose_name='título')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='conteúdo')),
                ('ocorrido_em', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='ocorrido em')),
                ('processado', models.BooleanField(db_index=True, default=False, verbose_name='processado')),
                ('tentativas', models.PositiveIntegerField(default=0, verbose_name='tentativas de entrega')),
                ('entregas_ok', models.PositiveIntegerField(default=0, verbose_name='entregas bem-sucedidas')),
                ('ultimo_erro', models.TextField(blank=True, default='', verbose_name='último erro')),
            ],
            options={
                'verbose_name': 'evento de integração',
                'verbose_name_plural': 'eventos de integração',
                'ordering': ['-ocorrido_em'],
                'indexes': [models.Index(fields=['processado', 'ocorrido_em'], name='integration_process_e3d25d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Integracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160, verbose_name='nome')),
                ('tipo', models.CharField(choices=[('LMS', 'LMS (Moodle, Cornerstone, Docebo)'), ('JIRA', 'Jira'), ('AZURE_DEVOPS', 'Azure DevOps'), ('TEAMS', 'Microsoft Teams'), ('SLACK', 'Slack'), ('GOOGLE_CALENDAR', 'Google Calendar'), ('OUTLOOK', 'Microsoft Outlook'), ('ERP', 'ERP (SAP, Oracle)'), ('RH', 'RH (Workday, Gupy, Senior)'), ('CRM', 'CRM (Salesforce)'), ('BI', 'Power BI / Tableau'), ('GITHUB', 'GitHub'), ('GITLAB', 'GitLab'), ('ESCO', 'Taxonomia ESCO / SFIA'), ('CERTIFICADORA', 'Plataforma de certificação')], db_index=True, max_length=20, verbose_name='tipo')),
                ('direcao', models.CharField(choices=[('ENTRADA', 'Entrada (importa para o SGP)'), ('SAIDA', 'Saída (exporta do SGP)'), ('BIDIRECIONAL', 'Bidirecional')], default='SAIDA', max_length=14, verbose_name='direção')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='descrição')),
                ('url_base', models.URLField(blank=True, default='', max_length=500, verbose_name='URL base')),
                ('autenticacao', models.CharField(choices=[('NENHUMA', 'Sem autenticação'), ('API_KEY', 'Chave de API'), ('BEARER', 'Token Bearer'), ('BASIC', 'Usuário e senha'), ('OAUTH2', 'OAuth 2.0'), ('WEBHOOK', 'URL de webhook (entrada)'), ('ARQUIVO', 'Arquivo / planilha')], default='API_KEY', max_length=12, verbose_name='autenticação')),
                ('credenciais', models.JSONField(blank=True, default=dict, verbose_name='credenciais')),
                ('cabecalhos', models.JSONField(blank=True, default=dict, verbose_name='cabeçalhos adicionais')),
                ('entidade_alvo', models.CharField(blank=True, default='', help_text='Ex.: tasks.task, portfolio.milestone, resources.timesheet.', max_length=60, verbose_name='entidade no SGP')),
                ('filtros', models.JSONField(blank=True, default=dict, verbose_name='filtros de seleção')),
                ('modo_simulacao', models.BooleanField(default=True, help_text='Quando ativo, o conector monta a requisição e registra o que seria enviado, sem chamar o sistema externo.', verbose_name='modo simulação')),
                ('ativa', models.BooleanField(db_index=True, default=False, verbose_name='ativa')),
                ('frequencia_minutos', models.PositiveIntegerField(default=60, verbose_name='frequência (min)')),
                ('proxima_sincronizacao', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='próxima sincronização')),
                ('status', models.CharField(choices=[('INATIVA', 'Inativa'), ('ATIVA', 'Ativa'), ('SINCRONIZANDO', 'Sincronizando'), ('ERRO', 'Com erro'), ('CONFIGURANDO', 'Em configuração')], db_index=True, default='CONFIGURANDO', max_length=14, verbose_name='status')),
                ('ultima_sincronizacao', models.DateTimeField(blank=True, null=True, verbose_name='última sincronização')),
                ('ultimo_erro', models.TextField(blank=True, default='', verbose_name='último erro')),
                ('total_execucoes', models.PositiveIntegerField(default=0, verbose_name='execuções')),
                ('total_sucesso', models.PositiveIntegerField(default=0, verbose_name='execuções com sucesso')),
                ('total_falha', models.PositiveIntegerField(default=0, verbose_name='execuções com falha')),
                ('itens_sincronizados', models.PositiveIntegerField(default=0, verbose_name='itens sincronizados')),
                ('cor', models.CharField(default='#2563EB', max_length=9, verbose_name='cor')),
                ('icone', models.CharField(default='plug', max_length=40, verbose_name='ícone')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integracoes', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
            ],
            options={
                'verbose_name': 'integração',
                'verbose_name_plural': 'integrações',
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='MapeamentoCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_origem', models.CharField(max_length=160, verbose_name='campo externo')),
                ('campo_destino', models.CharField(max_length=160, verbose_name='campo no SGP')),
                ('transformacao', models.CharField(choices=[('NENHUMA', 'Sem transformação'), ('MAIUSCULA', 'Maiúsculas'), ('MINUSCULA', 'Minúsculas'), ('TRIM', 'Remover espaços'), ('DATA', 'Converter para data'), ('NUMERO', 'Converter para número'), ('MOEDA', 'Converter para moeda'), ('BOOLEANO', 'Converter para sim/não'), ('ENUM', 'Traduzir valor (de/para)'), ('PESSOA', 'Localizar pessoa pelo e-mail'), ('SKILL', 'Localizar capacidade pelo nome')], default='NENHUMA', max_length=12, verbose_name='transformação')),
                ('traducao', models.JSONField(blank=True, default=dict, verbose_name='tabela de tradução')),
                ('valor_padrao', models.CharField(blank=True, default='', max_length=200, verbose_name='valor padrão')),
                ('obrigatorio', models.BooleanField(default=False, verbose_name='obrigatório')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('integracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapeamentos', to='integrations.integracao')),
            ],
            options={
                'verbose_name': 'mapeamento de campo',
                'verbose_name_plural': 'mapeamentos de campo',
                'ordering': ['integracao', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='SincronizacaoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='início')),
                ('fim', models.DateTimeField(blank=True, null=True, verbose_name='fim')),
                ('status', models.CharField(choices=[('EM_ANDAMENTO', 'Em andamento'), ('SUCESSO', 'Sucesso'), ('PARCIAL', 'Sucesso parcial'), ('FALHA', 'Falha'), ('SIMULADO', 'Simulado')], db_index=True, default='EM_ANDAMENTO', max_length=14, verbose_name='status')),
                ('operacao', models.CharField(default='IMPORTAR', max_length=12, verbose_name='operação')),
                ('itens_lidos', models.PositiveIntegerField(default=0, verbose_name='itens lidos')),
                ('itens_criados', models.PositiveIntegerField(default=0, verbose_name='criados')),
                ('itens_atualizados', models.PositiveIntegerField(default=0, verbose_name='atualizados')),
                ('itens_ignorados', models.PositiveIntegerField(default=0, verbose_name='ignorados')),
                ('itens_com_erro', models.PositiveIntegerField(default=0, verbose_name='com erro')),
                ('mensagem', models.TextField(blank=True, default='', verbose_name='mensagem')),
                ('erros', models.JSONField(blank=True, default=list, verbose_name='erros')),
                ('detalhes', models.JSONField(blank=True, default=dict, verbose_name='detalhes')),
                ('duracao_ms', models.PositiveIntegerField(default=0, verbose_name='duração (ms)')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('disparado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sincronizacoes', to=settings.AUTH_USER_MODEL)),
                ('integracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execucoes', to='integrations.integracao')),
            ],
            options={
                'verbose_name': 'execução de integração',
                'verbose_name_plural': 'execuções de integração',
                'ordering': ['-inicio'],
            },
        ),
        migrations.CreateModel(
            name='TokenAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=140, verbose_name='nome')),
                ('token', models.CharField(default=apps.integrations.models.gerar_token_integracao, max_length=64, unique=True)),
                ('escopos', models.JSONField(blank=True, default=list, verbose_name='escopos')),
                ('ip_permitido', models.CharField(blank=True, default='', max_length=120, verbose_name='IP permitido')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('expira_em', models.DateTimeField(blank=True, null=True, verbose_name='expira em')),
                ('ultimo_uso', models.DateTimeField(blank=True, null=True, verbose_name='último uso')),
                ('total_chamadas', models.PositiveIntegerField(default=0, verbose_name='chamadas')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_integracao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'credencial de API',
                'verbose_name_plural': 'credenciais de API',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, verbose_name='URL')),
                ('tentativa', models.PositiveIntegerField(default=1, verbose_name='tentativa')),
                ('status_code', models.PositiveIntegerField(blank=True, null=True, verbose_name='status HTTP')),
                ('sucesso', models.BooleanField(db_index=True, default=False, verbose_name='sucesso')),
                ('resposta', models.TextField(blank=True, default='', verbose_name='resposta')),
                ('erro', models.TextField(blank=True, default='', verbose_name='erro')),
                ('duracao_ms', models.PositiveIntegerField(default=0, verbose_name='duração (ms)')),
                ('simulado', models.BooleanField(default=False, verbose_name='simulado')),
                ('criado_em', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='integrations.eventointegracao')),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='core.webhook')),
            ],
            options={
                'verbose_name': 'entrega de webhook',
                'verbose_name_plural': 'entregas de webhook',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddIndex(
            model_name='integracao',
            index=models.Index(fields=['ativa', 'proxima_sincronizacao'], name='integration_ativa_93cf34_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mapeamentocampo',
            unique_together={('integracao', 'campo_destino')},
        ),
        migrations.AddIndex(
            model_name='sincronizacaolog',
            index=models.Index(fields=['integracao', '-inicio'], name='integration_integra_971326_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookentrega',
            index=models.Index(fields=['webhook', '-criado_em'], name='integration_webhook_952fde_idx'),
        ),
    ]
