# Generated by Django 6.0 on 2026-09-17 01:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_index=True, max_length=180, verbose_name='nome')),
                ('tipo', models.CharField(choices=[('HUMANO', 'Humano'), ('EQUIPAMENTO', 'Equipamento'), ('SOFTWARE', 'Software / Licença'), ('INSTALACAO', 'Instalação'), ('SERVICO', 'Serviço terceirizado'), ('MATERIAL', 'Material')], default='EQUIPAMENTO', max_length=16, verbose_name='tipo')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='descrição')),
                ('codigo', models.CharField(blank=True, default='', max_length=60, verbose_name='código/patrimônio')),
                ('custo_hora', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='custo/hora (R$)')),
                ('custo_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='custo unitário (R$)')),
                ('unidade', models.CharField(default='unidade', max_length=24, verbose_name='unidade')),
                ('quantidade_disponivel', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='quantidade disponível')),
                ('disponibilidade_percentual', models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='disponibilidade (%)')),
                ('data_disponivel_de', models.DateField(blank=True, null=True, verbose_name='disponível de')),
                ('data_disponivel_ate', models.DateField(blank=True, null=True, verbose_name='disponível até')),
                ('fornecedor', models.CharField(blank=True, default='', max_length=180, verbose_name='fornecedor')),
                ('localizacao', models.CharField(blank=True, default='', max_length=140, verbose_name='localização')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
                ('cor', models.CharField(default='#EC4899', max_length=9, verbose_name='cor')),
                ('icone', models.CharField(default='boxes', max_length=40, verbose_name='ícone')),
                ('atributos', models.JSONField(blank=True, default=dict, verbose_name='atributos')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'recurso',
                'verbose_name_plural': 'recursos',
                'ordering': ['tipo', 'nome'],
                'indexes': [models.Index(fields=['tipo', 'ativo'], name='resources_r_tipo_14f53a_idx')],
            },
        ),
        migrations.CreateModel(
            name='CapacidadeSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana_inicio', models.DateField(verbose_name='início da semana')),
                ('horas_disponiveis', models.DecimalField(decimal_places=2, default=40, max_digits=5, verbose_name='horas disponíveis')),
                ('motivo', models.CharField(blank=True, default='', max_length=120, verbose_name='motivo')),
                ('observacao', models.TextField(blank=True, default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacidades_semanais', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'capacidade semanal',
                'verbose_name_plural': 'capacidades semanais',
                'ordering': ['-semana_inicio'],
                'unique_together': {('user', 'semana_inicio')},
            },
        ),
        migrations.CreateModel(
            name='Alocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentual', models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='percentual de dedicação')),
                ('horas_planejadas', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='horas planejadas')),
                ('data_inicio', models.DateField(db_index=True, verbose_name='início')),
                ('data_fim', models.DateField(db_index=True, verbose_name='fim')),
                ('status', models.CharField(choices=[('PROPOSTA', 'Proposta'), ('CONFIRMADA', 'Confirmada'), ('EM_EXECUCAO', 'Em execução'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], db_index=True, default='CONFIRMADA', max_length=16)),
                ('modalidade', models.CharField(choices=[('PERFORMANCE', 'Performance imediata'), ('DESENVOLVIMENTO', 'Desenvolvimento'), ('MISTA', 'Mista (sênior + júnior)'), ('MANUAL', 'Manual')], default='MANUAL', max_length=20)),
                ('papel', models.CharField(blank=True, default='', max_length=120, verbose_name='papel no projeto')),
                ('justificativa', models.TextField(blank=True, default='', verbose_name='justificativa')),
                ('score_matching', models.FloatField(blank=True, null=True, verbose_name='score do motor de alocação')),
                ('override_manual', models.BooleanField(default=False, verbose_name='sobrepôs a recomendação')),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alocacoes_aprovadas', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alocacoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='portfolio.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='tasks.task')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to=settings.AUTH_USER_MODEL)),
                ('recurso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alocacoes', to='resources.recurso')),
            ],
            options={
                'verbose_name': 'alocação',
                'verbose_name_plural': 'alocações',
                'ordering': ['data_inicio', 'user__nome'],
                'indexes': [models.Index(fields=['user', 'data_inicio', 'data_fim'], name='resources_a_user_id_ca3276_idx'), models.Index(fields=['project', 'status'], name='resources_a_project_6b3090_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('user__isnull', False), ('recurso__isnull', False), _connector='OR'), name='alocacao_exige_user_ou_recurso')],
            },
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True, verbose_name='data')),
                ('horas', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='horas')),
                ('descricao', models.TextField(blank=True, default='', verbose_name='descrição')),
                ('atividade', models.CharField(blank=True, default='', max_length=80, verbose_name='atividade')),
                ('aprovado', models.BooleanField(db_index=True, default=False, verbose_name='aprovado')),
                ('aprovado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('aprovador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apontamentos_aprovados', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apontamentos', to='portfolio.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apontamentos', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apontamentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'apontamento de horas',
                'verbose_name_plural': 'apontamentos de horas',
                'ordering': ['-data', 'user__nome'],
                'indexes': [models.Index(fields=['user', 'data'], name='resources_t_user_id_78e04f_idx'), models.Index(fields=['project', 'data'], name='resources_t_project_02bb18_idx')],
            },
        ),
    ]
